print("-"*18)
print("Formatando strings")
print("-"*18)
print()
nome, idade = input("Entre com seu nome e idade separados por vírgula: ").split(",")
print()
print(nome, idade)
print()
print("Seu nome é "+ nome + " e sua idade é de "+ idade + " anos.")
print()
print(f"Seu nome é {nome} e sua idade é de {idade} anos.")
print()